language: sh

sudo: required

before_script:
    - sudo mkdir -p /ebrmain/bin
    - sudo mkdir -p /ebrmain/config
    - sudo mkdir -p /ebrmain/language
    - sudo mkdir -p /mnt/ext1
    - sudo mount --bind ./ /mnt/ext1
    - mkdir -p /mnt/ext1/system/bin
    - mkdir -p /mnt/ext1/system/config/settings
    - sudo bash -c "echo -e '#/bin/sh\necho "$*"\nexit 1' > /ebrmain/bin/dialog"
    - sudo chmod +x /ebrmain/bin/dialog
    - touch /mnt/ext1/system/config/global.cfg
    - sudo touch /ebrmain/language/en.txt

script:
    - sh -x Setup-openwith.app
