language: sh

sudo: required

before_script:
    - sudo cp -R test-env/ebrmain /
    - sudo mkdir -p /mnt/ext1
    - sudo mount --bind test-env/mnt/ext1 /mnt/ext1

#need to remove
    - sudo chmod +x /ebrmain/bin/dialog

script:
    - busybox sh -x Setup-openwith.app
