language: sh

sudo: required

before_install:
    - sudo apt-get -qq install busybox
    - sudo cp -R test-env/ebrmain /
    - sudo mkdir -p /mnt/ext1
    - sudo mount --bind test-env/mnt/ext1 /mnt/ext1

    - sudo chmod +x /ebrmain/bin/dialog

install:
    - mkdir -p /mnt/ext1/applications
    - cp Setup-openwith.app /mnt/ext1/applications/

script:
    - busybox sh /mnt/ext1/applications/Setup-openwith.app
    - [ -s /mnt/ext1/system/openwith_remove.app ]
