language: sh

sudo: required

addons:
  apt:
    packages: busybox

env:
  - TEST_ENV=test-env
  - TEST_ENV=test-env2

before_install:
  - sudo cp -R $TEST_ENV/ebrmain /
  - sudo mkdir -p /mnt/ext1
  - sudo mount --bind $TEST_ENV/mnt/ext1 /mnt/ext1
  - cp -R test-env/tmp/* /tmp

install:
  - mkdir -p /mnt/ext1/applications
  - mv Setup-openwith.app /mnt/ext1/applications/
    
script:
  - busybox sh -x /mnt/ext1/applications/Setup-openwith.app
  - test "-e ! /mnt/ext1/applications/Setup-openwith.app"
  - test -s /mnt/ext1/system/config/settings/personalize.json
  - test -s /mnt/ext1/system/config/settings/openwith.json
  - test -s /mnt/ext1/system/bin/openwith_apply.app
  - test -s /mnt/ext1/system/bin/openwith_clear.app
  - test -s /mnt/ext1/system/bin/openwith_remove.app
  - test -s /mnt/ext1/system/bin/openwith_fb2.app

  - busybox sh -x /mnt/ext1/system/bin/openwith_apply.app
  - busybox sh -x /mnt/ext1/system/bin/openwith_clear.app
  - busybox sh -x /mnt/ext1/system/bin/openwith_fb2.app
  - busybox sh -x /mnt/ext1/system/bin/openwith_remove.app
  - test "-e ! /mnt/ext1/system/config/settings/personalize.json"
  - test "-e ! /mnt/ext1/system/config/settings/openwith.json"
  - test "-e ! /mnt/ext1/system/config/settings/openwith.cfg"
  - test "-e ! /mnt/ext1/system/bin/openwith_apply.app"
  - test "-e ! /mnt/ext1/system/bin/openwith_clear.app"
  - test "-e ! /mnt/ext1/system/bin/openwith_remove.app"
  - test "-e ! /mnt/ext1/system/bin/openwith_fb2.app"
