language: sh

sudo: required

before_script:
    - sudo mkdir -p /ebrmain/config
    - sudo mkdir -p /ebrmain/language
    - mkdir -p /mnt/ext1/system/bin
    - mkdir -p /mnt/ext1/system/config/settings

script:
    - sh Setup-openwith.app
